name: Deploy buggy eShop dronjo

on:
  push:
    branches: [gh-pages]
  pull_request:
    branches: [gh-pages]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Introduce css bug
        run: |
          rm Dronjo/style.css

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/deploy-pages@v1

      - name: deploy
        run: |
          echo "ahaaa"
